### ISSUE TITLE
This must be accepted explicitly before updates for this repository can be applied.

### ISSUE THREAD

**Issue by ShagoY** [schirrmie/upm#3]
When a repo requests acceptance before the upgrade, upm does not display it.
Do you think you can add it?

```
Get:6 http://dl.ubnt.com/unifi/debian stable InRelease [3024 B]
E: Repository 'http://dl.ubnt.com/unifi/debian stable InRelease' changed its 'Codename' value from 'unifi-5.12' to 'unifi-5.13'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]
```

**Comment by schirrmie** [comment]
Hi,
sorry for my late answer. I never saw this and can't test this. Please try to add
`--allow-releaseinfo-change`
in the distribution config.
Maybe this help. But I don't know if this is good as default.

**Comment by ShagoY** [comment]
Hi,

I was waiting for my software repo to change so I could add/test your patch and it just happened but I discovered another strange behavior.

This time it's the official Debian repo that has changed.
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
18 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Repository 'http://ftp.debian.org/debian buster InRelease' changed its 'Version' value from '10.4' to '10.5'.
```

I don't see an update under UPM unless I manually perform an apt update directly on the host.
Contrary to my initial problem, it doesn't require validation here.

All my Debian VM/LXCs are subject to this issue.

Also, I don't understand or add the "--allow-releaseinfo-change" in the config distribution of my debian, I don't see the command that performs the apt update :/

Edit: I'm using version 0.1.2 Master.
Is the "Modularization" version "stable" at this stage?

**Comment by schirrmie** [comment]
Hi,
i updated the FAQ. Please see this
https://github.com/schirrmie/upm/blob/master/FAQ.md#automatic-apt-update

You find the update command under Global Settings > Distribution Config > Edit

![grafik](https://user-images.githubusercontent.com/7531415/90867944-707c1100-e396-11ea-9d7f-55310ebda272.png)

Please stay at the master branch. We are working on a permissions system but it take some time.

**Comment by ShagoY** [comment]
Finally I just re-enabled unattended-upgrades (Debian-Security) on my servers via ansible.
I'll wait for the inventory schedules and notifications in a future update to do only the "Update-Package-Lists" ;-D

Thank you.
